<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="10.6490" tests="16" failures="9">
  <testsuite name="Root Suite" timestamp="2021-12-11T21:02:14" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="express_authentication" timestamp="2021-12-11T21:02:14" tests="7" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\index.spec.js" time="4.5320" failures="2">
    <testcase name="express_authentication Should generate an API key and add it to file" time="0.5060" classname="Should generate an API key and add it to file">
    </testcase>
    <testcase name="express_authentication &quot;before each&quot; hook for &quot;Should generate 5 unique API Keys&quot;" time="2.0130" classname="&quot;before each&quot; hook for &quot;Should generate 5 unique API Keys&quot;">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\index.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="express_authentication &quot;after each&quot; hook for &quot;Should generate 5 unique API Keys&quot;" time="2.0130" classname="&quot;after each&quot; hook for &quot;Should generate 5 unique API Keys&quot;">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\index.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Operations" timestamp="2021-12-11T21:02:19" tests="0" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\operations.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test Operations Controller " timestamp="2021-12-11T21:02:19" tests="4" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\operations.spec.js" time="0.0610" failures="0">
    <testcase name="Operations Test Operations Controller  Test function Sum" time="0.0410" classname="Test function Sum">
    </testcase>
    <testcase name="Operations Test Operations Controller  Test function Substract" time="0.0060" classname="Test function Substract">
    </testcase>
    <testcase name="Operations Test Operations Controller  Test function multiply" time="0.0070" classname="Test function multiply">
    </testcase>
    <testcase name="Operations Test Operations Controller  Test function divide" time="0.0070" classname="Test function divide">
    </testcase>
  </testsuite>
  <testsuite name="payment check" timestamp="2021-12-11T21:02:19" tests="3" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js" time="6.0200" failures="5">
    <testcase name="payment check Should generate an random price" time="2.0040" classname="Should generate an random price">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="payment check &quot;after each&quot; hook for &quot;Should generate 5 random prices&quot;" time="0.0000" classname="&quot;after each&quot; hook for &quot;Should generate 5 random prices&quot;">
      <failure message="done() called multiple times" type="Error"><![CDATA[Error: done() called multiple times
    at C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js:34:23]]></failure>
    </testcase>
    <testcase name="payment check Should generate 5 random prices" time="2.0140" classname="Should generate 5 random prices">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="payment check &quot;after each&quot; hook for &quot;Should return 5 promo codes&quot;" time="0.0000" classname="&quot;after each&quot; hook for &quot;Should return 5 promo codes&quot;">
      <failure message="done() called multiple times" type="Error"><![CDATA[Error: done() called multiple times
    at C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js:34:23]]></failure>
    </testcase>
    <testcase name="payment check Should return 5 promo codes" time="2.0020" classname="Should return 5 promo codes">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Shipment" timestamp="2021-12-11T21:02:25" tests="0" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\shipment.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test Shipment Controller " timestamp="2021-12-11T21:02:25" tests="2" file="C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\shipment.spec.js" time="0.0360" failures="2">
    <testcase name="payment check &quot;after each&quot; hook in &quot;payment check&quot;" time="0.0000" classname="&quot;after each&quot; hook in &quot;payment check&quot;">
      <failure message="done() called multiple times" type="Error"><![CDATA[Error: done() called multiple times
    at C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\payment.spec.js:34:23]]></failure>
    </testcase>
    <testcase name="Shipment Test Shipment Controller  Test Function createShipment" time="0.0080" classname="Test Function createShipment">
    </testcase>
    <testcase name="Shipment Test Shipment Controller  Test Function changeStatus" time="0.0280" classname="Test Function changeStatus">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at C:\Users\Dell\Diplomado\ProyectoFinal\proyect\test\shipment.spec.js:25:37
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>